### ISSUE TITLE
Question about the prompt selection process.

### ISSUE THREAD

**Issue by Wangyulin-user** [yeerwen/UniSeg#2]
Thank you for your excellent work. The idea of the task prompt is very innovative, but I am curious about how you design and get the ground truth of the target feature Ftp, because I found out you use output embedding instead of input embedding of the task-specific prompt. Could you please describe the task selection process?

**Comment by Wangyulin-user** [comment]
Thank you for your excellent work. The idea of the task prompt is very innovative, but I am curious about how you design and get the ground truth of the target feature Ftp, because I found out you use output embedding instead of input embedding of the task-specific prompt. Could you please describe the task selection process?

**Comment by yeerwen** [comment]
Actually, we employ a universal prompt through the FUSE module to obtain a task-specific prompt for each task. The output of the FUSE module has N channels, each belonging to a task. Next, we select the used task-specific prompt by the task ID, since we know what the ongoing task is in this setting.

**Comment by Wangyulin-user** [comment]
I get it, thank you so much for your quick reply!
