### ISSUE TITLE
verse2020  merge dataset

### ISSUE THREAD

**Issue by XFivezzz** [yeerwen/UniSeg#8]
I am doing the task of verse 2020, and I have completed the Move splits_ The final. pkl step, when I merge with Python_ Each_ Sub_ Dataet.py, it seems to default to Task091_ MOTS, how should I modify merge_ Each_ Sub_ Dataet.py makes it Task037_ VerSe20binary. Can I skip this step and train directly?
![image](https://github.com/yeerwen/UniSeg/assets/93257077/1b59fc28-6902-4ee2-9b2f-0a5fda20bcc7)

**Comment by yeerwen** [comment]
Do you train only Ver2020 or do you need to follow our setup, i.e., joint training of 11 tasks? In the case of the former, you can use our Downstream code to fine-tune it, in the case of the latter, you need to follow the steps we provided to process the MOTS, VerSe20, BraTS21, Prastate, and AutoPET datasets in order, and then run the merge_each_sub_data.py file.

**Comment by XFivezzz** [comment]
I just want to train verse 2020, so what can I do directly?

**Comment by yeerwen** [comment]
If you are only training a task, you do not need to use our upstream task code. Instead, the downstream fine-tuning approach is more suitable because the benefits of pre-training can be enjoyed. Note that you need to rename the 'DoDNetPlans_plans_3D.pkl' and 'DoDNetData_plans_stage0' generated from the preprocessed VerSe dataset to 'nnUNetPlansv2.1_plans_3D.pkl' and 'nnUNetData_plans_v2.1_stage0', respectively, to avoid program errors.
